[[CURRENCIES]]
currency = "XOA"
issuer = "rGnv36JYcphGiNdofdHPUczYggBvAxZnAo"
name = "Xanora Coin"
desc = "Token for animal-friendly projects & running on fast XRPL payments."
icon = "https://u.jimcdn.com/cms/o/sd6ada8ea889a3f3b/userlayout/img/xanora-logo-ico.png?t=1744970696"

[CONTACT]
email = "info@xanora.network"
website = "https://www.xanora.network"
